[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm = "H8smav211zHmLvHBMwrvGkd2LtZ811Ban9HpHKpeuosp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jimohabdulateef/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
