[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "BgFk9iYaLydCe62an4JBQ9ccdv9nR9GG9aXD39nn18Dr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jimohabdulateef/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
